<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $categories = Category::all();

        foreach ($categories as $category) {
            $products = $this->getProductsForCategory($category);

            foreach ($products as $product) {
                Product::create([
                    'category_id' => $category->id,
                    'name' => $product['name'],
                    'slug' => Str::slug($product['name']),
                    'description' => $product['description'],
                    'price' => $product['price'],
                    'stock' => rand(5, 100),
                    'sku' => $product['sku'],
                    'weight' => $product['weight'],
                    'images' => $product['images'],
                    'is_active' => true,
                    'views' => rand(0, 1000),
                ]);
            }
        }
    }

    private function getProductsForCategory(Category $category): array
    {
        return match ($category->slug) {
            'football' => [
                [
                    'name' => 'Nike Premier League Football',
                    'description' => 'Official Nike Premier League football with superior grip and durability',
                    'price' => 750000,
                    'sku' => 'NIKE-PL-001',
                    'weight' => 0.45,
                    'images' => ['http://localhost:8000/images/products/nike-football-1.jpg', 'http://localhost:8000/images/products/nike-football-2.jpg'],
                ],
                [
                    'name' => 'Adidas Predator Football Boots',
                    'description' => 'Professional football boots with superior control and comfort',
                    'price' => 2500000,
                    'sku' => 'ADIDAS-PRED-001',
                    'weight' => 0.8,
                    'images' => ['http://localhost:8000/images/products/adidas-boots-1.jpg', 'http://localhost:8000/images/products/adidas-boots-2.jpg'],
                ],
                [
                    'name' => 'Manchester United Home Jersey',
                    'description' => 'Official Manchester United home jersey 2024/25 season',
                    'price' => 1200000,
                    'sku' => 'MU-HOME-001',
                    'weight' => 0.25,
                    'images' => ['http://localhost:8000/images/products/mu-jersey-1.jpg'],
                ],
                [
                    'name' => 'Football Training Cones Set',
                    'description' => 'Set of 20 training cones for football practice',
                    'price' => 150000,
                    'sku' => 'TRAIN-CONE-001',
                    'weight' => 1.2,
                    'images' => ['http://localhost:8000/images/products/training-cones-1.jpg'],
                ],
                [
                    'name' => 'Football Shin Guards',
                    'description' => 'Lightweight protective shin guards for football',
                    'price' => 200000,
                    'sku' => 'SHIN-GUARD-001',
                    'weight' => 0.3,
                    'images' => ['http://localhost:8000/images/products/shin-guards-1.jpg'],
                ],
                [
                    'name' => 'Football Goal Net',
                    'description' => 'Durable football goal net suitable for all weather',
                    'price' => 300000,
                    'sku' => 'GOAL-NET-001',
                    'weight' => 2.0,
                    'images' => ['http://localhost:8000/images/products/goal-net-1.jpg'],
                ],
                [
                    'name' => 'Football Gloves',
                    'description' => 'Professional goalkeeper gloves with excellent grip',
                    'price' => 400000,
                    'sku' => 'GK-GLOVES-001',
                    'weight' => 0.4,
                    'images' => ['http://localhost:8000/images/products/gk-gloves-1.jpg'],
                ],
            ],
            'basketball' => [
                [
                    'name' => 'Spalding NBA Basketball',
                    'description' => 'Official NBA basketball with authentic feel and bounce',
                    'price' => 800000,
                    'sku' => 'SPALDING-NBA-001',
                    'weight' => 0.6,
                    'images' => ['http://localhost:8000/images/products/spalding-ball-1.jpg', 'http://localhost:8000/images/products/spalding-ball-2.jpg'],
                ],
                [
                    'name' => 'Nike Air Jordan Basketball Shoes',
                    'description' => 'Iconic basketball shoes with superior performance',
                    'price' => 3000000,
                    'sku' => 'JORDAN-SHOE-001',
                    'weight' => 0.9,
                    'images' => ['http://localhost:8000/images/products/jordan-shoes-1.jpg', 'http://localhost:8000/images/products/jordan-shoes-2.jpg'],
                ],
                [
                    'name' => 'Lakers Home Jersey',
                    'description' => 'Official Los Angeles Lakers home jersey',
                    'price' => 1500000,
                    'sku' => 'LAKERS-HOME-001',
                    'weight' => 0.3,
                    'images' => ['http://localhost:8000/images/products/lakers-jersey-1.jpg'],
                ],
                [
                    'name' => 'Basketball Hoop Portable',
                    'description' => 'Adjustable portable basketball hoop for home use',
                    'price' => 2200000,
                    'sku' => 'HOOP-PORT-001',
                    'weight' => 25.0,
                    'images' => ['http://localhost:8000/images/products/portable-hoop-1.jpg'],
                ],
                [
                    'name' => 'Basketball Training Rebounder',
                    'description' => 'Training rebounder for practicing shooting',
                    'price' => 800000,
                    'sku' => 'REBOUNDER-001',
                    'weight' => 5.0,
                    'images' => ['http://localhost:8000/images/products/rebounder-1.jpg'],
                ],
                [
                    'name' => 'Basketball Shooting Sleeve',
                    'description' => 'Compression shooting sleeve for better performance',
                    'price' => 150000,
                    'sku' => 'SHOOT-SLEEVE-001',
                    'weight' => 0.1,
                    'images' => ['http://localhost:8000/images/products/shooting-sleeve-1.jpg'],
                ],
                [
                    'name' => 'Basketball Pump',
                    'description' => 'Professional basketball pump with pressure gauge',
                    'price' => 100000,
                    'sku' => 'BALL-PUMP-001',
                    'weight' => 0.5,
                    'images' => ['http://localhost:8000/images/products/ball-pump-1.jpg'],
                ],
            ],
            'badminton' => [
                [
                    'name' => 'Yonex Arcsaber 11 Racket',
                    'description' => 'Professional badminton racket with excellent control',
                    'price' => 2800000,
                    'sku' => 'YONEX-ARC11-001',
                    'weight' => 0.35,
                    'images' => ['http://localhost:8000/images/products/yonex-racket-1.jpg', 'http://localhost:8000/images/products/yonex-racket-2.jpg'],
                ],
                [
                    'name' => 'Victor Shuttlecocks',
                    'description' => 'Professional feather shuttlecocks - pack of 12',
                    'price' => 200000,
                    'sku' => 'VICTOR-SHUT-001',
                    'weight' => 0.3,
                    'images' => ['http://localhost:8000/images/products/victor-shuttlecocks-1.jpg'],
                ],
                [
                    'name' => 'Badminton Court Shoes',
                    'description' => 'Non-marking badminton court shoes with excellent grip',
                    'price' => 1200000,
                    'sku' => 'COURT-SHOE-001',
                    'weight' => 0.8,
                    'images' => ['http://localhost:8000/images/products/court-shoes-1.jpg'],
                ],
                [
                    'name' => 'Badminton Racket Bag',
                    'description' => 'Professional badminton racket bag with multiple compartments',
                    'price' => 400000,
                    'sku' => 'RACKET-BAG-001',
                    'weight' => 0.8,
                    'images' => ['http://localhost:8000/images/products/racket-bag-1.jpg'],
                ],
                [
                    'name' => 'Badminton Net',
                    'description' => 'Official tournament badminton net',
                    'price' => 300000,
                    'sku' => 'BAD-NET-001',
                    'weight' => 1.0,
                    'images' => ['http://localhost:8000/images/products/badminton-net-1.jpg'],
                ],
                [
                    'name' => 'Badminton Grip Tape',
                    'description' => 'Professional grip tape for racket handle',
                    'price' => 50000,
                    'sku' => 'GRIP-TAPE-001',
                    'weight' => 0.05,
                    'images' => ['http://localhost:8000/images/products/grip-tape-1.jpg'],
                ],
            ],
            'running' => [
                [
                    'name' => 'Nike Air Zoom Running Shoes',
                    'description' => 'Lightweight running shoes with responsive cushioning',
                    'price' => 2200000,
                    'sku' => 'NIKE-ZOOM-001',
                    'weight' => 0.7,
                    'images' => ['http://localhost:8000/images/products/nike-running-1.jpg', 'http://localhost:8000/images/products/nike-running-2.jpg'],
                ],
                [
                    'name' => 'Adidas Running Shorts',
                    'description' => 'Moisture-wicking running shorts for comfort',
                    'price' => 300000,
                    'sku' => 'ADIDAS-SHORT-001',
                    'weight' => 0.2,
                    'images' => ['http://localhost:8000/images/products/adidas-shorts-1.jpg'],
                ],
                [
                    'name' => 'Garmin GPS Running Watch',
                    'description' => 'GPS running watch with heart rate monitor',
                    'price' => 4500000,
                    'sku' => 'GARMIN-GPS-001',
                    'weight' => 0.15,
                    'images' => ['http://localhost:8000/images/products/garmin-watch-1.jpg'],
                ],
                [
                    'name' => 'Running Hydration Belt',
                    'description' => 'Lightweight hydration belt for long runs',
                    'price' => 250000,
                    'sku' => 'HYDRO-BELT-001',
                    'weight' => 0.3,
                    'images' => ['http://localhost:8000/images/products/hydration-belt-1.jpg'],
                ],
                [
                    'name' => 'Compression Running Socks',
                    'description' => 'Compression socks for better blood circulation',
                    'price' => 150000,
                    'sku' => 'COMP-SOCK-001',
                    'weight' => 0.1,
                    'images' => ['http://localhost:8000/images/products/compression-socks-1.jpg'],
                ],
                [
                    'name' => 'Running Headband',
                    'description' => 'Moisture-wicking headband for running',
                    'price' => 75000,
                    'sku' => 'RUN-HEADBAND-001',
                    'weight' => 0.05,
                    'images' => ['http://localhost:8000/images/products/headband-1.jpg'],
                ],
                [
                    'name' => 'Running Armband Phone Holder',
                    'description' => 'Adjustable armband for phone during runs',
                    'price' => 120000,
                    'sku' => 'ARM-PHONE-001',
                    'weight' => 0.15,
                    'images' => ['http://localhost:8000/images/products/armband-1.jpg'],
                ],
            ],
            'gym-equipment' => [
                [
                    'name' => 'Adjustable Dumbbell Set',
                    'description' => 'Adjustable dumbbells 5-50kg with rack',
                    'price' => 3500000,
                    'sku' => 'DUMBBELL-SET-001',
                    'weight' => 50.0,
                    'images' => ['http://localhost:8000/images/products/dumbbell-set-1.jpg', 'http://localhost:8000/images/products/dumbbell-set-2.jpg'],
                ],
                [
                    'name' => 'Resistance Bands Set',
                    'description' => 'Set of 5 resistance bands with different resistance levels',
                    'price' => 200000,
                    'sku' => 'RESIST-BAND-001',
                    'weight' => 0.8,
                    'images' => ['http://localhost:8000/images/products/resistance-bands-1.jpg'],
                ],
                [
                    'name' => 'Yoga Mat Premium',
                    'description' => 'High-quality yoga mat with excellent grip',
                    'price' => 350000,
                    'sku' => 'YOGA-MAT-001',
                    'weight' => 1.2,
                    'images' => ['http://localhost:8000/images/products/yoga-mat-1.jpg'],
                ],
                [
                    'name' => 'Pull-up Bar',
                    'description' => 'Doorway pull-up bar for home workouts',
                    'price' => 400000,
                    'sku' => 'PULLUP-BAR-001',
                    'weight' => 2.0,
                    'images' => ['http://localhost:8000/images/products/pullup-bar-1.jpg'],
                ],
                [
                    'name' => 'Kettlebell 20kg',
                    'description' => 'Cast iron kettlebell for strength training',
                    'price' => 800000,
                    'sku' => 'KETTLEBELL-20-001',
                    'weight' => 20.0,
                    'images' => ['http://localhost:8000/images/products/kettlebell-1.jpg'],
                ],
                [
                    'name' => 'Foam Roller',
                    'description' => 'High-density foam roller for muscle recovery',
                    'price' => 200000,
                    'sku' => 'FOAM-ROLLER-001',
                    'weight' => 0.6,
                    'images' => ['http://localhost:8000/images/products/foam-roller-1.jpg'],
                ],
                [
                    'name' => 'Weight Bench',
                    'description' => 'Adjustable weight bench for home gym',
                    'price' => 1500000,
                    'sku' => 'WEIGHT-BENCH-001',
                    'weight' => 25.0,
                    'images' => ['http://localhost:8000/images/products/weight-bench-1.jpg'],
                ],
            ],
            'tennis' => [
                [
                    'name' => 'Wilson Pro Staff Tennis Racket',
                    'description' => 'Professional tennis racket used by pros',
                    'price' => 2500000,
                    'sku' => 'WILSON-PROSTAFF-001',
                    'weight' => 0.32,
                    'images' => ['http://localhost:8000/images/products/wilson-racket-1.jpg'],
                ],
                [
                    'name' => 'Tennis Balls Set',
                    'description' => 'Official tennis balls - pack of 4',
                    'price' => 80000,
                    'sku' => 'TENNIS-BALL-001',
                    'weight' => 0.25,
                    'images' => ['http://localhost:8000/images/products/tennis-balls-1.jpg'],
                ],
                [
                    'name' => 'Tennis Court Shoes',
                    'description' => 'Professional tennis shoes with lateral support',
                    'price' => 1800000,
                    'sku' => 'TENNIS-SHOE-001',
                    'weight' => 0.9,
                    'images' => ['http://localhost:8000/images/products/tennis-shoes-1.jpg'],
                ],
                [
                    'name' => 'Tennis Racket Bag',
                    'description' => 'Tennis racket bag with multiple compartments',
                    'price' => 500000,
                    'sku' => 'TENNIS-BAG-001',
                    'weight' => 1.0,
                    'images' => ['http://localhost:8000/images/products/tennis-bag-1.jpg'],
                ],
                [
                    'name' => 'Tennis String',
                    'description' => 'Professional tennis string for racket',
                    'price' => 150000,
                    'sku' => 'TENNIS-STRING-001',
                    'weight' => 0.1,
                    'images' => ['http://localhost:8000/images/products/tennis-string-1.jpg'],
                ],
                [
                    'name' => 'Tennis Wristband',
                    'description' => 'Moisture-wicking wristband for tennis',
                    'price' => 50000,
                    'sku' => 'TENNIS-WRIST-001',
                    'weight' => 0.05,
                    'images' => ['http://localhost:8000/images/products/wristband-1.jpg'],
                ],
            ],
            'swimming' => [
                [
                    'name' => 'Speedo Competition Swimsuit',
                    'description' => 'Professional competition swimsuit with drag reduction',
                    'price' => 1200000,
                    'sku' => 'SPEEDO-COMP-001',
                    'weight' => 0.2,
                    'images' => ['http://localhost:8000/images/products/speedo-suit-1.jpg'],
                ],
                [
                    'name' => 'Swimming Goggles',
                    'description' => 'Anti-fog swimming goggles with UV protection',
                    'price' => 200000,
                    'sku' => 'SWIM-GOGGLE-001',
                    'weight' => 0.1,
                    'images' => ['http://localhost:8000/images/products/goggles-1.jpg'],
                ],
                [
                    'name' => 'Swimming Cap',
                    'description' => 'Silicone swimming cap for reduced drag',
                    'price' => 100000,
                    'sku' => 'SWIM-CAP-001',
                    'weight' => 0.05,
                    'images' => ['http://localhost:8000/images/products/swim-cap-1.jpg'],
                ],
                [
                    'name' => 'Swimming Kickboard',
                    'description' => 'Training kickboard for swimming technique',
                    'price' => 150000,
                    'sku' => 'KICKBOARD-001',
                    'weight' => 0.5,
                    'images' => ['http://localhost:8000/images/products/kickboard-1.jpg'],
                ],
                [
                    'name' => 'Pool Fins',
                    'description' => 'Training fins for swimming practice',
                    'price' => 250000,
                    'sku' => 'POOL-FINS-001',
                    'weight' => 0.8,
                    'images' => ['http://localhost:8000/images/products/pool-fins-1.jpg'],
                ],
                [
                    'name' => 'Waterproof Swimming Bag',
                    'description' => 'Waterproof bag for swimming gear',
                    'price' => 180000,
                    'sku' => 'WATERPROOF-BAG-001',
                    'weight' => 0.3,
                    'images' => ['http://localhost:8000/images/products/waterproof-bag-1.jpg'],
                ],
            ],
            'cycling' => [
                [
                    'name' => 'Road Bike 21 Speed',
                    'description' => 'Professional road bike with 21-speed gear system',
                    'price' => 8500000,
                    'sku' => 'ROAD-BIKE-001',
                    'weight' => 12.0,
                    'images' => ['http://localhost:8000/images/products/road-bike-1.jpg', 'http://localhost:8000/images/products/road-bike-2.jpg'],
                ],
                [
                    'name' => 'Cycling Helmet',
                    'description' => 'Safety cycling helmet with ventilation',
                    'price' => 400000,
                    'sku' => 'CYCLE-HELMET-001',
                    'weight' => 0.3,
                    'images' => ['http://localhost:8000/images/products/cycle-helmet-1.jpg'],
                ],
                [
                    'name' => 'Cycling Shorts',
                    'description' => 'Padded cycling shorts for comfort',
                    'price' => 300000,
                    'sku' => 'CYCLE-SHORT-001',
                    'weight' => 0.2,
                    'images' => ['http://localhost:8000/images/products/cycle-shorts-1.jpg'],
                ],
                [
                    'name' => 'Bike Lock',
                    'description' => 'Heavy-duty bike lock for security',
                    'price' => 250000,
                    'sku' => 'BIKE-LOCK-001',
                    'weight' => 1.5,
                    'images' => ['http://localhost:8000/images/products/bike-lock-1.jpg'],
                ],
                [
                    'name' => 'Cycling Gloves',
                    'description' => 'Padded cycling gloves for better grip',
                    'price' => 150000,
                    'sku' => 'CYCLE-GLOVE-001',
                    'weight' => 0.15,
                    'images' => ['http://localhost:8000/images/products/cycle-gloves-1.jpg'],
                ],
                [
                    'name' => 'Bike Water Bottle',
                    'description' => 'Sports water bottle with bike mount',
                    'price' => 80000,
                    'sku' => 'BIKE-BOTTLE-001',
                    'weight' => 0.2,
                    'images' => ['http://localhost:8000/images/products/bike-bottle-1.jpg'],
                ],
                [
                    'name' => 'Bike Repair Kit',
                    'description' => 'Essential bike repair kit with tools',
                    'price' => 200000,
                    'sku' => 'BIKE-REPAIR-001',
                    'weight' => 0.8,
                    'images' => ['http://localhost:8000/images/products/bike-repair-1.jpg'],
                ],
            ],
            default => [],
        };
    }
}
